In [2]:
import keras
keras.__version__

'3.0.5'

In [1]:
import tensorflow as tf

2024-03-13 08:52:05.545551: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-13 08:52:05.731354: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-13 08:52:06.354679: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-13 08:52:12.881575: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
from keras.preprocessing.text import Tokenizer

ModuleNotFoundError: No module named 'keras.preprocessing.text'

In [1]:
# magic command for reload 
%load_ext autoreload
%autoreload 2

from utils import *
from dataset import *

2024-03-11 19:01:52.277398: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-11 19:01:52.323235: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-11 19:01:52.323296: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-11 19:01:52.324780: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-11 19:01:52.332712: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-11 19:01:52.333851: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
# Example usage:
image_dir = 'dataset/formula_images_processed/'
image_list_file = 'dataset/im2latex_train_filter.lst'
label_file = 'dataset/im2latex_formulas.norm.lst'

In [25]:
# get all formulas
formulas = get_formulas(label_file)

# # get max length of formulas
# max_len = get_max_length(formulas)

# get a histogram of formula lengths
hist = get_formula_length_histogram(formulas)

# set max_len to where formula occurs at least 100 times using histogram
max_len = get_max_length(formulas, min_occurrences=100)

tokenizer = TokenizerWrap(formulas, max_len, reverse=True)

after init: len(self.word_index) 0
{}
after special token: len(self.word_index) 415
after fiting: len(self.word_index) 418


In [19]:
tokenizer.tokens.shape

(103559, 150)

In [26]:
tokenizer.word_index

{'<UNK>': 1,
 '2': 2,
 '1': 3,
 'frac': 4,
 'i': 5,
 'a': 6,
 'n': 7,
 '0': 8,
 'x': 9,
 'd': 10,
 'm': 11,
 'r': 12,
 'c': 13,
 'e': 14,
 't': 15,
 'l': 16,
 'k': 17,
 's': 18,
 'mu': 19,
 'p': 20,
 'left': 21,
 'right': 22,
 'j': 23,
 'b': 24,
 'g': 25,
 'f': 26,
 '3': 27,
 'alpha': 28,
 'partial': 29,
 'phi': 30,
 'z': 31,
 '4': 32,
 'q': 33,
 'h': 34,
 'prime': 35,
 'pi': 36,
 'lambda': 37,
 'delta': 38,
 'nu': 39,
 'gamma': 40,
 'u': 41,
 'v': 42,
 'mathrm': 43,
 'operatorname': 44,
 'cal': 45,
 'y': 46,
 'psi': 47,
 'sigma': 48,
 'beta': 49,
 'bar': 50,
 'int': 51,
 'array': 52,
 'theta': 53,
 'omega': 54,
 'o': 55,
 'hat': 56,
 'w': 57,
 'sqrt': 58,
 'sum': 59,
 'rho': 60,
 'tilde': 61,
 'tau': 62,
 'epsilon': 63,
 'bf': 64,
 'xi': 65,
 'eta': 66,
 'quad': 67,
 '5': 68,
 'vec': 69,
 'begin': 70,
 'end': 71,
 'infty': 72,
 '6': 73,
 'rangle': 74,
 'dot': 75,
 'pm': 76,
 'varphi': 77,
 'chi': 78,
 '8': 79,
 'kappa': 80,
 'qquad': 81,
 'cdot': 82,
 'equiv': 83,
 'langle': 84,
 'ove

In [31]:
tokenizer.tokens[]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [11]:
tokenizer.tokens[0]

array([418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418,
       418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418,
       418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418,
       418, 418, 418,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [22]:
image_size = (224, 224)
batch_size = 32
# max_sequence_length = get_max_length(formulas, min_occurrences=100)

dataset = BaseDataset(image_dir, image_list_file, label_file, 
                      image_size=image_size, batch_size=batch_size, max_sequence_length=max_len)

In [11]:
len(dataset[0][1])

1

In [9]:
dataset.labels_padded.shape

(103559, 150)

In [11]:
(tokenizer.tokens == dataset.labels_padded).sum()

12905411

In [12]:
eq = tf.equal(tokenizer.tokens, dataset.labels_padded)
eq

2024-03-11 16:36:36.243241: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: UNKNOWN ERROR (100)
2024-03-11 16:36:36.246038: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 62135400 exceeds 10% of free system memory.
2024-03-11 16:36:36.521545: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 62135400 exceeds 10% of free system memory.


<tf.Tensor: shape=(103559, 150), dtype=bool, numpy=
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])>

In [30]:
tokenizer.tokens[0]

array([54, 66, 75, 13, 19, 46, 17, 19, 91, 54, 66, 75, 13, 19, 38, 46, 17,
       19, 38, 91, 19, 19, 38,  7, 19, 38, 19, 19, 19, 38, 30, 41, 38, 38,
       19,  7, 30, 35, 18, 41, 19, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [11]:
dataset.labels_padded[0]

array([51, 63, 72, 10, 16, 43, 14, 16, 88, 51, 63, 72, 10, 16, 35, 43, 14,
       16, 35, 88, 16, 16, 35,  4, 16, 35, 16, 16, 16, 35, 27, 38, 35, 35,
       16,  4, 27, 32, 15, 38, 16,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [15]:
dataset.labels_padded[2]

array([106,  40,  43,  34,  55,  20,  26, 132,  59,   7,   8, 106,  25,
         7,   4,   6,   7,   2,   2,   7,   3,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [16]:
dataset.labels_padded[4]

array([18, 18, 15,  6, 15,  2, 36, 58,  7, 68,  3,  7, 68,  2,  7, 68, 27,
       21, 58,  7, 58, 50,  7, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [23]:
dataset[0]

(array([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         ...,
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          ...,
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],
 
 
        [

In [24]:
dataset[0][1]

['\\widetilde \\gamma _ { \\mathrm { h o p f } } \\simeq \\sum _ { n > 0 } \\widetilde { G } _ { n } { \\frac { ( - a ) ^ { n } } { 2 ^ { 2 n - 1 } } }\n',
 '( { \\cal L } _ { a } g ) _ { i j } = 0 , \\ \\ \\ \\ ( { \\cal L } _ { a } H ) _ { i j k } = 0 ,\n',
 'S _ { s t a t } = 2 \\pi \\sqrt { N _ { 5 } ^ { ( 1 ) } N _ { 5 } ^ { ( 2 ) } N _ { 5 } ^ { ( 3 ) } } \\left( \\sqrt { n } + \\sqrt { \\bar { n } } \\right)\n',
 '\\hat { N } _ { 3 } = \\sum \\sp f _ { j = 1 } a _ { j } \\sp { \\dagger } a _ { j } \\, .\n',
 '\\, ^ { * } d \\, ^ { * } H = \\kappa \\, ^ { * } d \\phi = J _ { B } .\n',
 '{ \\frac { \\phi ^ { \\prime \\prime } } { A } } + { \\frac { 1 } { A } } \\left( - { \\frac { 1 } { 2 } } { \\frac { A ^ { \\prime } } { A } } + 2 { \\frac { B ^ { \\prime } } { B } } + { \\frac { 2 } { r } } \\right) \\phi ^ { \\prime } - { \\frac { 2 } { r ^ { 2 } } } \\phi - \\lambda \\phi ( \\phi ^ { 2 } - \\eta ^ { 2 } ) = 0 \\, .\n',
 '\\partial _ { \\mu } ( F ^ { \\mu \\nu } - e j ^ { \\mu

In [30]:
tokenizer.caption_to_tokens(dataset[0][1][0])

array([[  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [109,  43,  46,  37,  58,  23,  29, 135,  62,  10,  11, 109,  28,
         10,   7,   9,  10,   5,   5,  10,   6,   0,   0,   0,   0,   0,
       

In [31]:
dataset[0][1][0]

'\\widetilde \\gamma _ { \\mathrm { h o p f } } \\simeq \\sum _ { n > 0 } \\widetilde { G } _ { n } { \\frac { ( - a ) ^ { n } } { 2 ^ { 2 n - 1 } } }\n'

In [32]:
tokenizer.tokens_to_caption(tokenizer.caption_to_tokens(dataset[0][1][0]))

'underline mathrm y lambda sqrt j partial circ tau d m underline alpha d n x d i i d a <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>'